### ISSUE TITLE
Compile Error with Arduino Board

### ISSUE THREAD

**Issue by ARD-DW** [leollo98/AD7606#5]
I tried compile for the Arduino Uno R4 Minima, Mega2560 and Raspberry Pi Pico boards but failed with compilation error. Could u please help to fix thoses issues so I can use this library.
![微信截图_20240127173008](https://github.com/leollo98/AD7606/assets/157881465/56efbf23-8629-43e0-9374-c3a1be621be6)

**Comment by leollo98** [comment]
It's seens to be a problem with your IDE or library installation.
